"use client";

import { useState } from "react";
import {
  Calendar,
  CreditCard,
  Download,
  FileText,
  FolderOpen,
  ImageIcon,
  Loader2,
  MoreHorizontal,
} from "lucide-react";

import {
  DS_TABLE_HEAD,
  DS_TABLE_WRAP,
  DS_TD_PRIMARY,
  DS_TD_SECONDARY,
  DS_TH,
  DS_TR,
} from "@/app/admin/designSystem";
import {
  RecentExport,
  recordTypeLabel,
  statusBadgeClass,
} from "@/components/admin/records/recordsTypes";

type RecordsRecentExportsTableProps = {
  exports: RecentExport[];
  loading?: boolean;
};

function TypeIcon({ type }: { type: string }) {
  const cls = "h-3.5 w-3.5";
  switch (type) {
    case "clinical_notes":
      return <FileText className={cls} />;
    case "evaluations":
      return <Calendar className={cls} />;
    case "billing":
      return <CreditCard className={cls} />;
    case "imaging":
      return <ImageIcon className={cls} />;
    default:
      return <FolderOpen className={cls} />;
  }
}

export default function RecordsRecentExportsTable({
  exports: rows,
  loading,
}: RecordsRecentExportsTableProps) {
  const [menuId, setMenuId] = useState<string | null>(null);

  return (
    <div className="rounded-xl border border-gray-200 bg-white shadow-sm">
      <div className="flex items-center justify-between border-b border-gray-100 px-5 py-4">
        <div>
          <h3 className="text-sm font-semibold text-gray-900">Recent Exports</h3>
        </div>
        <button type="button" className="text-xs font-medium text-emerald-700 hover:underline">
          View All →
        </button>
      </div>
      <div className={DS_TABLE_WRAP}>
        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-sm">
            <thead className={DS_TABLE_HEAD}>
              <tr>
                <th className={DS_TH}>Patient</th>
                <th className={DS_TH}>Generated By</th>
                <th className={DS_TH}>Date</th>
                <th className={DS_TH}>Record Types</th>
                <th className={DS_TH}>Pages</th>
                <th className={DS_TH}>Status</th>
                <th className={`${DS_TH} w-20`}>Action</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={7} className="px-6 py-8 text-center text-gray-500">
                    Loading…
                  </td>
                </tr>
              ) : rows.length === 0 ? (
                <tr>
                  <td colSpan={7} className="px-6 py-8 text-center text-gray-500">
                    No exports yet
                  </td>
                </tr>
              ) : (
                rows.map((row) => (
                  <tr key={row.id} className={DS_TR}>
                    <td className={DS_TD_PRIMARY}>
                      <div className="flex items-center gap-2">
                        <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-gray-100 text-xs font-semibold text-gray-600">
                          {row.patient_avatar_initials}
                        </span>
                        <div>
                          <p className="font-medium text-gray-900">{row.patient_name}</p>
                          <p className="text-xs text-gray-500">{row.patient_pt_id}</p>
                        </div>
                      </div>
                    </td>
                    <td className={DS_TD_SECONDARY}>{row.generated_by}</td>
                    <td className={`${DS_TD_SECONDARY} whitespace-nowrap`}>
                      {row.exported_at}
                    </td>
                    <td className={DS_TD_PRIMARY}>
                      <div className="flex flex-wrap gap-1">
                        {row.record_types.map((t) => (
                          <span
                            key={t}
                            className="inline-flex items-center gap-1 rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600"
                            title={recordTypeLabel(t)}
                          >
                            <TypeIcon type={t} />
                          </span>
                        ))}
                      </div>
                    </td>
                    <td className={`${DS_TD_PRIMARY} tabular-nums`}>
                      {row.page_count || "—"}
                    </td>
                    <td className={DS_TD_PRIMARY}>
                      <span
                        className={`inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-medium ${statusBadgeClass(row.status)}`}
                      >
                        {row.status === "processing" ? (
                          <Loader2 className="h-3 w-3 animate-spin" />
                        ) : null}
                        {row.status.charAt(0).toUpperCase() + row.status.slice(1)}
                      </span>
                    </td>
                    <td className="relative px-3 py-2">
                      <div className="flex items-center gap-1">
                        {row.file_url ? (
                          <a
                            href={row.file_url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="rounded p-1.5 text-emerald-700 hover:bg-emerald-50"
                            aria-label="Download"
                          >
                            <Download className="h-4 w-4" />
                          </a>
                        ) : null}
                        <button
                          type="button"
                          className="rounded p-1.5 text-gray-400 hover:bg-gray-100"
                          onClick={() =>
                            setMenuId(menuId === row.id ? null : row.id)
                          }
                          aria-label="More actions"
                        >
                          <MoreHorizontal className="h-4 w-4" />
                        </button>
                        {menuId === row.id ? (
                          <div className="absolute right-2 top-10 z-10 min-w-[140px] rounded-lg border border-gray-200 bg-white py-1 shadow-lg">
                            <button
                              type="button"
                              className="block w-full px-3 py-2 text-left text-sm text-gray-700 hover:bg-gray-50"
                            >
                              Re-generate
                            </button>
                            <button
                              type="button"
                              className="block w-full px-3 py-2 text-left text-sm text-gray-700 hover:bg-gray-50"
                            >
                              Email
                            </button>
                            <button
                              type="button"
                              className="block w-full px-3 py-2 text-left text-sm text-gray-700 hover:bg-gray-50"
                            >
                              View Details
                            </button>
                          </div>
                        ) : null}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
      <div className="border-t border-gray-100 px-5 py-3">
        <button type="button" className="text-xs font-medium text-emerald-700 hover:underline">
          View All Exports →
        </button>
      </div>
    </div>
  );
}
