-- MIGRATION 1 — Seed table for all orthopedic special tests.
-- Run once in the Supabase SQL editor (plain INSERTs: re-running duplicates rows).

CREATE TABLE IF NOT EXISTS orthopedic_special_tests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  region text NOT NULL,
  subcategory text,
  test_name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

INSERT INTO orthopedic_special_tests (region, subcategory, test_name) VALUES
-- CERVICAL SPINE
('Cervical Spine','Radiculopathy','Spurling''s Test'),
('Cervical Spine','Radiculopathy','Cervical Distraction Test'),
('Cervical Spine','Radiculopathy','Upper Limb Tension Test (ULTT)'),
('Cervical Spine','Radiculopathy','Shoulder Abduction Relief Sign'),
('Cervical Spine','Radiculopathy','Valsalva Maneuver'),
('Cervical Spine','Radiculopathy','Cervical Quadrant Test'),
('Cervical Spine','Myelopathy','Hoffman''s Sign'),
('Cervical Spine','Myelopathy','Babinski Sign'),
('Cervical Spine','Myelopathy','Clonus'),
('Cervical Spine','Myelopathy','Lhermitte''s Sign'),
('Cervical Spine','Instability','Sharp-Purser Test'),
('Cervical Spine','Instability','Alar Ligament Test'),
('Cervical Spine','Instability','Transverse Ligament Stress Test'),
('Cervical Spine','Thoracic Outlet','Adson''s Test'),
('Cervical Spine','Thoracic Outlet','Roos Test'),
('Cervical Spine','Thoracic Outlet','Wright''s Hyperabduction Test'),
('Cervical Spine','Thoracic Outlet','Costoclavicular Test'),
-- THORACIC SPINE
('Thoracic Spine',NULL,'Slump Test'),
('Thoracic Spine',NULL,'Rib Spring Test'),
('Thoracic Spine',NULL,'Thoracic Compression Test'),
('Thoracic Spine',NULL,'Thoracic Rotation Provocation Test'),
('Thoracic Spine',NULL,'Schepelmann''s Test'),
-- SHOULDER
('Shoulder','Impingement','Neer''s Test'),
('Shoulder','Impingement','Hawkins-Kennedy Test'),
('Shoulder','Impingement','Painful Arc Test'),
('Shoulder','Impingement','Empty Can Test'),
('Shoulder','Impingement','Speed''s Test'),
('Shoulder','Rotator Cuff','Drop Arm Test'),
('Shoulder','Rotator Cuff','Full Can Test'),
('Shoulder','Rotator Cuff','Empty Can Test'),
('Shoulder','Rotator Cuff','External Rotation Lag Sign'),
('Shoulder','Rotator Cuff','Hornblower''s Sign'),
('Shoulder','Rotator Cuff','Belly Press Test'),
('Shoulder','Rotator Cuff','Lift-Off Test'),
('Shoulder','Rotator Cuff','Bear Hug Test'),
('Shoulder','Labral Pathology','O''Brien''s Test'),
('Shoulder','Labral Pathology','Crank Test'),
('Shoulder','Labral Pathology','Biceps Load I'),
('Shoulder','Labral Pathology','Biceps Load II'),
('Shoulder','Labral Pathology','Compression Rotation Test'),
('Shoulder','Labral Pathology','Anterior Slide Test'),
('Shoulder','Instability','Apprehension Test'),
('Shoulder','Instability','Relocation Test'),
('Shoulder','Instability','Surprise Test'),
('Shoulder','Instability','Sulcus Sign'),
('Shoulder','Instability','Load and Shift Test'),
('Shoulder','Biceps Tendon','Speed''s Test'),
('Shoulder','Biceps Tendon','Yergason''s Test'),
('Shoulder','AC Joint','Cross Body Adduction Test'),
('Shoulder','AC Joint','AC Shear Test'),
-- ELBOW
('Elbow','Lateral Epicondylitis','Cozen''s Test'),
('Elbow','Lateral Epicondylitis','Mill''s Test'),
('Elbow','Lateral Epicondylitis','Maudsley''s Test'),
('Elbow','Medial Epicondylitis','Golfer''s Elbow Test'),
('Elbow','Ligament Stability','Valgus Stress Test'),
('Elbow','Ligament Stability','Varus Stress Test'),
('Elbow','Ligament Stability','Moving Valgus Stress Test'),
('Elbow','Cubital Tunnel','Tinel''s at Cubital Tunnel'),
('Elbow','Cubital Tunnel','Elbow Flexion Test'),
-- WRIST & HAND
('Wrist & Hand','Carpal Tunnel','Phalen''s Test'),
('Wrist & Hand','Carpal Tunnel','Reverse Phalen''s Test'),
('Wrist & Hand','Carpal Tunnel','Tinel''s Sign'),
('Wrist & Hand','Carpal Tunnel','Durkan Compression Test'),
('Wrist & Hand','TFCC','TFCC Compression Test'),
('Wrist & Hand','TFCC','Ulnar Fovea Sign'),
('Wrist & Hand','De Quervain''s','Finkelstein Test'),
('Wrist & Hand','De Quervain''s','Eichhoff Test'),
('Wrist & Hand','Thumb','CMC Grind Test'),
('Wrist & Hand','Finger Ligaments','Valgus Stress Test'),
('Wrist & Hand','Finger Ligaments','Varus Stress Test'),
-- LUMBAR SPINE
('Lumbar Spine','Discogenic/Radiculopathy','Straight Leg Raise'),
('Lumbar Spine','Discogenic/Radiculopathy','Crossed Straight Leg Raise'),
('Lumbar Spine','Discogenic/Radiculopathy','Slump Test'),
('Lumbar Spine','Discogenic/Radiculopathy','Femoral Nerve Stretch Test'),
('Lumbar Spine','Instability','Prone Instability Test'),
('Lumbar Spine','SI Joint','Gaenslen''s Test'),
('Lumbar Spine','SI Joint','Compression Test'),
('Lumbar Spine','SI Joint','Distraction Test'),
('Lumbar Spine','SI Joint','Thigh Thrust Test'),
('Lumbar Spine','SI Joint','Sacral Thrust Test'),
('Lumbar Spine','SI Joint','FABER Test'),
('Lumbar Spine','Facet Joint','Kemp''s Test'),
('Lumbar Spine','Facet Joint','Quadrant Test'),
-- HIP
('Hip','FAI/Labrum','FADIR Test'),
('Hip','FAI/Labrum','FABER Test'),
('Hip','FAI/Labrum','Scour Test'),
('Hip','FAI/Labrum','Log Roll Test'),
('Hip','Gluteal Tendinopathy','Trendelenburg Sign'),
('Hip','Gluteal Tendinopathy','Single Leg Stance Test'),
('Hip','Hamstring','Bent Knee Stretch Test'),
('Hip','Hamstring','Puranen-Orava Test'),
('Hip','Hip Flexor','Thomas Test'),
('Hip','Hip Flexor','Ely''s Test'),
-- KNEE
('Knee','Meniscus','McMurray Test'),
('Knee','Meniscus','Thessaly Test'),
('Knee','Meniscus','Apley''s Compression Test'),
('Knee','Meniscus','Joint Line Tenderness'),
('Knee','ACL','Lachman Test'),
('Knee','ACL','Anterior Drawer Test'),
('Knee','ACL','Pivot Shift Test'),
('Knee','PCL','Posterior Drawer Test'),
('Knee','PCL','Posterior Sag Sign'),
('Knee','MCL','Valgus Stress Test'),
('Knee','LCL','Varus Stress Test'),
('Knee','Patellofemoral','Patellar Grind Test'),
('Knee','Patellofemoral','Clarke''s Sign'),
('Knee','Patellofemoral','Patellar Apprehension Test'),
('Knee','IT Band','Noble Compression Test'),
('Knee','IT Band','Ober''s Test'),
-- ANKLE & FOOT
('Ankle & Foot','Lateral Ankle Ligaments','Anterior Drawer Test'),
('Ankle & Foot','Lateral Ankle Ligaments','Talar Tilt Test'),
('Ankle & Foot','Syndesmosis','Kleiger Test'),
('Ankle & Foot','Syndesmosis','Squeeze Test'),
('Ankle & Foot','Achilles Tendon','Thompson Test'),
('Ankle & Foot','Plantar Fascia','Windlass Test'),
('Ankle & Foot','Tarsal Tunnel','Tinel''s Sign'),
('Ankle & Foot','Foot Structure','Navicular Drop Test'),
('Ankle & Foot','Foot Structure','Jack''s Test'),
-- BALANCE & NEUROLOGICAL
('Balance & Neurological',NULL,'Romberg Test'),
('Balance & Neurological',NULL,'Sharpened Romberg'),
('Balance & Neurological',NULL,'Single Leg Balance'),
('Balance & Neurological',NULL,'Tandem Walking'),
('Balance & Neurological',NULL,'Berg Balance Assessment'),
('Balance & Neurological',NULL,'Timed Up and Go (TUG)'),
('Balance & Neurological',NULL,'Five Times Sit to Stand'),
-- FUNCTIONAL MOVEMENT
('Functional Movement',NULL,'Double Leg Squat'),
('Functional Movement',NULL,'Single Leg Squat'),
('Functional Movement',NULL,'Step Down Test'),
('Functional Movement',NULL,'Overhead Squat'),
('Functional Movement',NULL,'Lunge Assessment'),
('Functional Movement',NULL,'Heel Raise Test'),
('Functional Movement',NULL,'Single Leg Hop'),
('Functional Movement',NULL,'Triple Hop Test'),
('Functional Movement',NULL,'Crossover Hop Test'),
('Functional Movement',NULL,'Y Balance Test'),
('Functional Movement',NULL,'Star Excursion Balance Test'),
('Functional Movement',NULL,'Knee to Wall Test');
